### ISSUE TITLE
Build fails with nodejs 6+

### ISSUE THREAD

**Issue by rhalff** [flowhub/the-graph#296]
The build fails on node 6+, updating the stylus dependency will solve it.

``` javascript
$ grunt exec:build_stylus
./themes/the-graph-dark.styl ./themes/the-graph-light.styl
Running "exec:build_stylus" (exec) task
>> path.js:7
>>     throw new TypeError('Path must be a string. Received ' + inspect(path));
>>     ^
>> 
>> TypeError: Path must be a string. Received undefined
>>     at assertPath (path.js:7:11)
>>     at extname (path.js:1433:5)
>>     at Object.<anonymous> (/srv/psichi/git/the-graph/node_modules/stylus/bin/stylus:412:25)
>>     at Module._compile (module.js:556:32)
>>     at Object.Module._extensions..js (module.js:565:10)
>>     at Module.load (module.js:473:32)
>>     at tryModuleLoad (module.js:432:12)
>>     at Function.Module._load (module.js:424:3)
>>     at Module.runMain (module.js:590:10)
>>     at run (bootstrap_node.js:394:7)
>> Exited with code: 1.
Warning: Task "exec:build_stylus" failed. Use --force to continue.
```

See: https://github.com/stylus/stylus/issues/2173

Updating all dependencies also seems to work fine.

For a quick dependency update [ncu](https://www.npmjs.com/package/npm-check-updates) might be useful:

``` coffee
 $ ncu
[..................] / :
 noflo                  ^0.5.21  →   ^0.7.9 
 coffeeify               ^1.2.0  →   ^2.0.1 
 glob                    ^6.0.1  →   ^7.0.6 
 grunt                   ~0.4.5  →   ~1.0.1 
 grunt-browserify        ~4.0.1  →   ~5.0.0 
 grunt-contrib-connect  ~0.11.2  →   ~1.0.2 
 grunt-contrib-jshint   ~0.11.3  →   ~1.0.0 
 grunt-contrib-watch     ~0.6.1  →   ~1.0.0 
 grunt-exec              ~0.4.6  →   ~1.0.0 
 stylus                 ~0.52.4  →  ~0.54.5 
```

**Comment by jonnor** [comment]
Can you provide a PR with the updated dependencies that you've tested?

**Comment by peter254** [comment]
Upgrading the dependencies helps, but the the following error occurs (during "npm run build"):
...
Running "browserify:libs" (browserify) task
>> Error: Cannot find module './src/list' from '/Users/peter/Documents/DeepLearning/testing/the-graph/node_modules/fbp-manifest'

Any ideas how to get around that?

**Comment by jonnor** [comment]
Fixed in master. Thanks @rhalff !
