### ISSUE TITLE
installing dependecies on linux fails

### ISSUE THREAD

**Issue by kazamatzuri** [flowhub/the-graph#391]
Steps:
1. on ubuntu 19.10
2. clone repo
3. run `yarn install`
```
node-pre-gyp info check checked for "/home/kazamatzuri/libs/the-graph/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/kazamatzuri/libs/the-graph/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:228:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/kazamatzuri/libs/the-graph/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:223:5)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:456:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:223:5)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:309:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:290:11)
node-pre-gyp ERR! System Linux 5.5.2-arch1-1
node-pre-gyp ERR! command "/home/kazamatzuri/.nvm/versions/node/v12.14.1/bin/node" "/home/kazamatzuri/libs/the-graph/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/kazamatzuri/libs/the-graph/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
```

**Comment by innovia** [comment]
same on a mac

**Comment by bergie** [comment]
canvas-prebuilt seems to be no longer maintained. We should probably switch to the regular `canvas` lib.
